# https://taskfile.dev

version: '3'

env:
  PACKAGE: clcoevt

tasks:
  default:
    desc: show tasks
    cmds:
      - task --list-all
    silent: true

  Is_venv_activated:
    internal: true
    preconditions:
      - sh: test -n "$VIRTUAL_ENV"
        msg: |
          Activate venv before this task.  Use the following command:
          Linux, MacOS:
              .venv/Scripts/Activate
          Windows:
              .venv\Scripts\Activate

  lint:
    desc: run linter
    deps: [ Is_venv_activated ]
    cmds:
      - ruff check

  format:
    desc: run formatter
    deps: [ Is_venv_activated ]
    cmds:
      - ruff format

  build:
    desc: build the package
    cmds:
      - uv build

  test:
    desc: run tests on the src
    deps: [ Is_venv_activated ]
    cmds:
      - nox

  test-package:
    desc: run tests on the installed package
    deps: [ Is_venv_activated ]
    cmds:
      - nox -f noxfile-package.py

  update-project:
    desc: Update this project
    cmds:
      - uv sync
