# https://taskfile.dev

version: '3'

env:
  PACKAGE: clcoevt

tasks:
  default:
    cmds:
      - task: info
      - task: list
    silent: true

  info:
    cmds:
      - 'echo Task {{.TASK_VERSION}}'
      - 'echo Taskfile: {{.TASKFILE}}'
    silent: true

  list:
    cmds:
      - 'task -l -t {{.TASKFILE}}'
    silent: true

  taskfile-path:
    cmds:
      - 'echo {{.TASKFILE}}'
    silent: true

  lint:
    desc: run linter
    cmds:
      - uv run ruff check

  format:
    desc: run formatter
    cmds:
      - uv run ruff format

  build:
    desc: build the package
    cmds:
      - uv build

  test:
    desc: run tests on the src
    env:
      UV_VENV_CLEAR: 1
    cmds:
      - uv run nox

  test-package:
    desc: run tests on the installed package
    env:
        UV_VENV_CLEAR: 1
    cmds:
      - uv run nox -f noxfile-package.py

  update-project:
    desc: Update this project
    cmds:
      - uv sync
