# https://taskfile.dev

version: '3'

env:
  PACKAGE: clcoevt

tasks:
  default:
    desc: show tasks
    cmds:
      - task --list-all
    silent: true

  lint:
    desc: run linter
    cmds:
      - ruff check

  format:
    desc: run formatter
    cmds:
      - ruff format

  build:
    desc: build the package
    cmds:
      - uv build

  install:
    desc: install the package
    cmds:
      - uv pip install --no-index --find-links=./dist {{.PACKAGE}}

  uninstall:
    desc: uninstall the package
    cmds:
      - uv pip uninstall {{.PACKAGE}}

  reinstall:
    desc: reinstall the package
    cmds:
      - uv pip install --force-reinstall --no-index --find-links=./dist {{.PACKAGE}}

  reload:
    desc: build and reinstall the package
    cmds:
      - task: lint
      - task: format
      - task: build
      - task: reinstall

  test:
    desc: run test
    cmds:
      - uv run -m unittest discover -s test
