HOST="localhost"
PORT=12345
ALLOW=true

[my_table]
HOST="tablehost"
PORT=12399
ALLOW=true

[table.nestedtable]
HOST="nestedtable"
PORT=12388
ALLOW=true

[dottedkey]
server.HOST="dottedkey"
server.PORT=12377
server.ALLOW=true
